### ISSUE TITLE
Build fails with newer Gradle version (5.1) because leftShift << operator is not supported.

### ISSUE THREAD

**Issue by the-sauce** [jojomickymack/missing-homework#1]
Couldn't build it from repo checkout using IntelliJ and Gradle 5.1; I will try to come up with a solution.

[errlog.txt](https://github.com/jojomickymack/missing-homework/files/2838046/errlog.txt)

EDIT: Giving up for now; my attempts ended in a horrible mess of missing dependencies. I am not a Gradle/groovy expert though.

**Comment by jojomickymack** [comment]
oh, I built this (and all of the other examples here) using gradle 4.10.2 - I'll install gradle 5.1 and fix it.

Looks like the issue is the << in that texture packer task - it's directly from the libgdx documentation.

[https://github.com/libgdx/libgdx/wiki/Texture-packer](https://github.com/libgdx/libgdx/wiki/Texture-packer)

I've actually never used it and the project builds fine with gradle 5 when it's removed - I'll remove it from each of the projects. Thanks for pointing that out!
